### PR TITLE
Draft PR for review of my work

### PR DESCRIPTION
**Pull request by shefali12-ab**
Created a Draft PR .

### CODE REVIEW

**Comment by KartikSoneji** [comment]
@shefali12-ab while this is a draft PR, you have the source and destination backwards.
You need to open a pull request to merge into `HarshKapadia2:main` from `shefali12-ab:main`.
It still makes sense to merge this PR since your fork is behind the original repository.

So, in summary:
- Merge this pull request
- Read up on how to create a pull request. [FreeCodeCamp has a nice article](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/)
- Create a new draft Pull Request from **your feature branch** (that has your commits) to the **upstream's main branch** (`HarshKapadia2/main`)
  Remember, your pull request should contain commits made by you.

**Comment by shefali12-ab** [comment]
okay @KartikSoneji  will do it.

**Comment by shefali12-ab** [comment]
@KartikSoneji  i have made required changes, I am facing issue in pushing those changes in my repository which I have forked .
all the changes I made was in main branch , when these changes were pushed into my repository then only I am able to create draft pull request.please see  the attached screenshot 
issue

**Comment by shefali12-ab** [comment]
issue2

**Comment by KartikSoneji** [comment]
Why don't you refer to git basics itself?
https://harshkapadia2.github.io/git_basics/#_git_push

**Comment by shefali12-ab** [comment]
@KartikSoneji  I have read the documentation but the problem i am getting was I am not able to push the changes which I have made in the repository that I have forked. I have also searched this issue on StackOverflow and run required command but still not getting it. 
isu

**Pull request merged**
